class ASTNode;//
class ASTProgramNode;//
class ASTClassNode;//
class ASTConstructNode;//
class ASTFunctionNode;
class ASTTypeNode;
class ASTBlockNode;//
class ASTStmtNode;
class ASTExprStmtNode;
class ASTExprNode;
class ASTFuncExprNode;
class ASTArrayExprNode;
class ASTMemberExprNode;
class ASTSingleExprNode;
class ASTNewExprNode;
class ASTBinaryExprNode;
class ASTTernaryExprNode;
class ASTAssignExprNode;
class ASTLiterExprNode;
class ASTAtomExprNode;
class ASTIfStmtNode;
class ASTWhileStmtNode;
class ASTForStmtNode;
class ASTFlowStmtNode;
class ASTContinueStmtNode;
class ASTBreakStmtNode;
class ASTReturnStmtNode;
class ASTVarStmtNode;
class ASTNewTypeNode;

